Repository Dulce-Work-Schedule/2018.1-Dulce_Schedule, pull requests merged in 2018-06, with the labels that each got.

#50 38 39 servidores
  .gitignore
  .travis.yml
  Client/.gitignore
  Client/test.sh
  Client/test/schedule.test.js
  Client/test/test.schedule.js
  Docker/Prod/.keep
  Docs/issue_template.md
  Docs/pull_request_template.md
  Environments/Development/Client/Dockerfile
  Environments/Development/Server/Dockerfile
  Environments/Development/Variables/mongo.env
  Environments/Development/Variables/rabbitmq.env
  Environments/Development/build.yml
  Environments/Development/start-deps.yml
  Environments/Development/start-schedule.yml
  Environments/Production/Client/Dockerfile
  Environments/Production/Server/Dockerfile
  Environments/Production/build.yml
  Environments/Test/Client/Dockerfile
  Environments/Test/Server/Dockerfile
  Environments/Test/Variables/coveralls.env
  Environments/Test/Variables/mongo.env
  Environments/Test/Variables/rabbitmq.env
  Environments/Test/build.yml
  Environments/Test/start-deps.yml
  Environments/Test/start-schedule.yml
  guia_de_instalacao.md
  script_coveralls.sh
  utils/deploy.sh
  utils/script_coveralls.sh
Labels: 0-DevOps, 1-Infraestrutura, 2-Deploy Contínuo, 3-Task, 4-Débito Técnico, 5-Intermediário

#51 49 Testes Unitários
  Server/plg_schedule.js
  Server/test/schedule.test.js
Labels: 0-Colaborador Externo, 1-Viabilidade Técnica, 2-Teste, 3-Task

#52 Fix #34 Criar usuario
  Client/api.js
  Server/package-lock.json
  Server/package.json
  Server/plg_schedule.js
  Server/test/schedule.test.js
  Server/test/valid_entrys_for_schedule_tests.json
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Débito Técnico, 5-Intermediário

#56 54 55 list by sector
  Client/api.js
  Server/plg_schedule.js
  Server/test/schedule.test.js
Labels: 0-Developers, 1-Produto, 3-Task, 4-Adicionado, 5-Intermediário
